export enum RainEnum {
  PatchyRainPossible = 'Patchy rain possible',
  PatchyFreezingDrizzlePossible = 'Patchy freezing drizzle possible',
  PatchyLightDrizzle = 'Patchy light drizzle',
  LightDrizzle = 'Light drizzle',
  FreezingDrizzle = 'Freezing drizzle',
  HeavyFreezingDrizzle = 'Heavy freezing drizzle',
  PatchyLightRain = 'Patchy light rain',
  LightRain = 'Light rain',
  ModerateRainAtTimes = 'Moderate rain at times',
  ModerateRain = 'Moderate rain',
  HeavyRainAtTimes = 'Heavy rain at times',
  HeavyRain = 'Heavy rain',
  LightFreezingRain = 'Light freezing rain',
  ModerateOrHeavyFreezingRain = 'Moderate or heavy freezing rain',
  LightRainShower = 'Light rain shower',
  ModerateOrHeavyRainShower = 'Moderate or heavy rain shower',
  TorrentialRainShower = 'Torrential rain shower',
  LightSleetShowers = 'Light sleet showers',
  ModerateOrHeavySleetShowers = 'Moderate or heavy sleet showers',
}
