export enum SnowEnum {
  LightSnow = 'Light snow',
  ModerateSnow = 'Moderate snow',
  HeavySnow = 'Heavy snow',
  LightSleet = 'Light sleet',
  ModerateOrHeavySleet = 'Moderate or heavy sleet',
  ModerateOrHeavySnowShowers = 'Moderate or heavy snow showers',
  PatchySleetPossible = 'Patchy sleet possible',
  PatchySnowpossible = 'Patchy snow possible',
  PatchyLightSnow = 'Patchy light snow',
  PatchyModerateSnow = 'Patchy moderate snow',
  PatchyHeavySnow = 'Patchy heavy snow',
  BlowingSnow = 'Blowing snow',
  Blizzard = 'Blizzard',
  FreezingFog = 'Freezing fog',
  IcePellets = 'Ice pellets',
  LightSnowShowers = 'Light snow showers',
  LightShowersOfIcePellets = 'Light showers of ice pellets',
  ModerateOrHeavyShowersOfIcePellets = 'Moderate or heavy showers of ice pellets',
}
